# Generated by Django 5.2.4 on 2025-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("account_id", models.AutoField(primary_key=True, serialize=False)),
                ("account_name", models.CharField(max_length=255)),
                (
                    "account_owner_alias",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "number_of_employees",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "billing_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_street",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_state_province",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_zip_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "shipping_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_street",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_state_province",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_zip_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "account",
                "ordering": ["account_name"],
            },
        ),
    ]
