# Generated by Django 5.1.11 on 2025-07-17 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_auto_20250711_1112"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("account_id", models.AutoField(primary_key=True, serialize=False)),
                ("account_name", models.CharField(max_length=255)),
                (
                    "account_owner_alias",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "billing_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_street",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_state_province",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_zip_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "shipping_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_street",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_state_province",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_zip_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_account_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_accounts",
                        to="accounts.account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="core.client",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "account",
                "ordering": ["account_name"],
                "indexes": [
                    models.Index(fields=["tenant"], name="idx_account_tenant"),
                    models.Index(fields=["owner"], name="idx_account_owner"),
                ],
            },
        ),
    ]
