# Generated by Django 5.1.11 on 2025-07-17 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0003_auto_20250711_1112"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_account_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["tenant", "account_name"], name="idx_account_tenant_name"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["tenant", "industry"], name="idx_account_tenant_industry"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["tenant", "owner"], name="idx_account_tenant_owner"
            ),
        ),
    ]
