# Generated by Django 5.2.4 on 2025-07-31 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_column="owner_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="parent_account",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_account_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_accounts",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="core.client",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["tenant"], name="idx_account_tenant"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["owner"], name="idx_account_owner"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_account_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["tenant", "account_name"], name="idx_account_tenant_name"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["tenant", "industry"], name="idx_account_tenant_industry"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["tenant", "owner"], name="idx_account_tenant_owner"
            ),
        ),
    ]
