# Generated by Django 5.1.11 on 2025-07-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_idx_account_tenant_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="number_of_employees",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
