# Generated by Django 5.1.11 on 2025-07-17 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_idx_account_tenant_created_and_more"),
        ("core", "0003_auto_20250711_1112"),
        ("opportunities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_deal_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["tenant", "stage"], name="idx_deal_tenant_stage"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["tenant", "close_date"], name="idx_deal_tenant_close_date"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["tenant", "amount"], name="idx_deal_tenant_amount"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["tenant", "account"], name="idx_deal_tenant_account"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["tenant", "owner"], name="idx_deal_tenant_owner"
            ),
        ),
    ]
