# Generated by Django 5.1.11 on 2025-07-23 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_number_of_employees"),
        ("contacts", "0002_contact_idx_contact_tenant_created_and_more"),
        ("core", "0006_move_models_to_tenant_core"),
        ("opportunities", "0002_deal_idx_deal_tenant_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                db_column="primary_contact_id",
                help_text="Primary contact for this deal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_deals",
                to="contacts.contact",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["primary_contact"], name="idx_deal_primary_contact"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["tenant", "primary_contact"], name="idx_deal_tenant_contact"
            ),
        ),
    ]
