# Generated by Django 5.2.4 on 2025-08-06 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("contact_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "mailing_street",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mailing_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mailing_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mailing_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        db_column="account_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "contact",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
