# Generated by Django 5.2.4 on 2025-07-31 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contact_owner",
            field=models.ForeignKey(
                blank=True,
                db_column="contact_owner_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts_contact_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_column="owner_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                db_column="reports_to_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportees",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="tenant",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="core.client",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["tenant"], name="idx_contact_tenant"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["account"], name="idx_contact_account"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["owner"], name="idx_contact_owner"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["reports_to"], name="idx_contact_reports_to"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_contact_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["tenant", "last_name"], name="idx_contact_tenant_lastname"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["tenant", "email"], name="idx_contact_tenant_email"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["tenant", "account"], name="idx_contact_tenant_account"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["tenant", "owner"], name="idx_contact_tenant_owner"
            ),
        ),
    ]
