# Generated by Django 5.2.4 on 2025-08-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_inbox", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.AddField(
            model_name="message",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="team_inbox.attachment"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="internal_notes",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="team_inbox.internalnote"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment_set",
                to="team_inbox.message",
            ),
        ),
        migrations.AlterField(
            model_name="internalnote",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note_set",
                to="team_inbox.message",
            ),
        ),
    ]
