# Generated by Django 5.2.4 on 2025-08-07 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_inbox", "0002_remove_message_conversation_message_attachments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="team_inbox.conversation",
            ),
        ),
    ]
