# Generated by Django 5.2.4 on 2025-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_inbox", "0003_message_conversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channelaccount",
            name="email",
        ),
        migrations.RemoveField(
            model_name="inbox",
            name="email",
        ),
        migrations.AddField(
            model_name="channelaccount",
            name="identifier",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="inbox",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inbox",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="channelaccount",
            name="expires_in",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="channelaccount",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
