# Generated by Django 5.2.4 on 2025-08-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_inbox", "0004_remove_channelaccount_email_remove_inbox_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelaccount",
            name="subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
