# Generated by Django 5.2.4 on 2025-08-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_inbox", "0005_channelaccount_subscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="team_inboxes",
            field=models.ManyToManyField(
                blank=True, related_name="teammates", to="team_inbox.inbox"
            ),
        ),
    ]
