# Generated by Django 5.2.4 on 2025-09-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_inbox", "0006_teammember_last_seen_teammember_team_inboxes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="assigned_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="assigned_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
