# Generated by Django 5.1.11 on 2025-07-17 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_idx_account_tenant_created_and_more"),
        ("core", "0003_auto_20250711_1112"),
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_lead_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["tenant", "lead_status"], name="idx_lead_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["tenant", "last_name"], name="idx_lead_tenant_lastname"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["tenant", "email"], name="idx_lead_tenant_email"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["tenant", "lead_owner"], name="idx_lead_tenant_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["tenant", "score"], name="idx_lead_tenant_score"
            ),
        ),
    ]
