# Generated by Django 5.1.11 on 2025-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_idx_lead_tenant_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Company name as entered during lead creation (before conversion)",
                max_length=255,
                null=True,
            ),
        ),
    ]
