# Generated by Django 5.0.6 on 2025-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tenants",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="core.client"
            ),
        ),
    ]
