# Generated by Django 5.0.6 on 2025-07-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_tenants"),
    ]

    operations = [
        # Remove duplicate tables from public schema
        migrations.RunSQL(
            "DROP TABLE IF EXISTS core_auditlog CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS core_userrole CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS core_role CASCADE;",
            reverse_sql="",
        ),
    ]
