# Generated by Django 5.1.11 on 2025-07-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20250711_1112"),
    ]

    operations = [
        # These models were moved to tenant_core app
        # No actual database changes needed since the models don't exist in this schema
    ]
