# Generated by Django 5.1.11 on 2025-07-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_moved_models"),
    ]

    operations = [
        # This migration cleans up the migration state
        # All role/user role models have been moved to tenant_core
    ]
