# Generated by Django 5.1.11 on 2025-07-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20250717_1252"),
    ]

    operations = [
        # Use state_operations to tell Django the models are gone from this app
        # but don't actually try to delete them from the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="Role"),
                migrations.DeleteModel(name="UserRole"),
                migrations.DeleteModel(name="AuditLog"),
            ],
            database_operations=[
                # No database operations needed since models were moved, not deleted
            ],
        ),
    ]
