# Generated by Django 5.1.11 on 2025-07-16 13:36

from django.db import migrations

import apps.tenant_core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20250711_1112"),
        ("tenant_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantUser",
            fields=[],
            options={
                "verbose_name": "Tenant User",
                "verbose_name_plural": "Tenant Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.user",),
            managers=[
                ("objects", apps.tenant_core.models.TenantUserManager()),
            ],
        ),
    ]
