# Generated by Django 5.1.11 on 2025-07-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_core", "0002_tenantuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.JSONField(default=list),
        ),
    ]
