# Generated by Django 5.1.11 on 2025-07-17 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_core", "0003_fix_permissions_field_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user"], name="idx_auditlog_user"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="idx_auditlog_action"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["model_name"], name="idx_auditlog_model"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["timestamp"], name="idx_auditlog_timestamp"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="idx_auditlog_user_timestamp"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="idx_auditlog_action_timestamp"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["role_type"], name="idx_role_type"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["is_active"], name="idx_role_active"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["created_at"], name="idx_role_created"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["user"], name="idx_userrole_user"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role"], name="idx_userrole_role"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["is_active"], name="idx_userrole_active"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["assigned_at"], name="idx_userrole_assigned"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "is_active"], name="idx_userrole_user_active"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["role", "is_active"], name="idx_userrole_role_active"
            ),
        ),
    ]
